### PR TITLE
resource/schema: Ensure invalid attribute default value errors are raised

### LINKED ISSUE #930: Incorrect element type of default list or map value in schema causes all default computed values of schema to be silently set to `null`
### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.5.0
```

### Relevant provider source code

```go
type ExampleResourceModel struct {
	ConfigurableAttribute types.String `tfsdk:"configurable_attribute"`
	Defaulted             types.String `tfsdk:"defaulted"`
	Id                    types.String `tfsdk:"id"`
	Foo                   []FooEntry   `tfsdk:"foo"`
}

type FooEntry struct {
}

func (r *ExampleResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "Example resource",

		Attributes: map[string]schema.Attribute{
			"configurable_attribute": schema.StringAttribute{
				MarkdownDescription: "Example configurable attribute",
				Optional:            true,
			},
			"defaulted": schema.StringAttribute{
				MarkdownDescription: "Example configurable attribute with default value",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString("example value when not configured"),
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Example identifier",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"foo": schema.ListNestedAttribute{
				MarkdownDescription: "test",
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{},
				},
				Computed: true,
				Default:  listdefault.StaticValue(types.ListValueMust(types.Int64Type, []attr.Value{})),
			},
		},
	}
}

```

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    scaffolding = {
      source = "edu/scaffolding"
    }
  }
}

provider "scaffolding" {}

resource "scaffolding_example" "example" {
  configurable_attribute = "some-value"
}

output "test" {
  value = scaffolding_example.example
}
```

### Expected Behavior
`output.test` should have `defaulted` set to `"example value when not configured"`

### Actual Behavior

`output.test.defaulted` is `null`

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # scaffolding_example.example will be created
  + resource "scaffolding_example" "example" {
      + configurable_attribute = "some-value"
      + id                     = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + test = {
      + configurable_attribute = "some-value"
      + defaulted              = null
      + foo                    = null
      + id                     = (known after apply)
    }
```

When commenting out `foo` in the schema and the model, the correct values appear:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # scaffolding_example.example will be created
  + resource "scaffolding_example" "example" {
      + configurable_attribute = "some-value"
      + defaulted              = "example value when not configured"
      + id                     = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + test = {
      + configurable_attribute = "some-value"
      + defaulted              = "example value when not configured"
      + id                     = (known after apply)
    }
```

I am fairly new to Terraform plugins and golang, so I could be holding it wrong. But I think this case should at least raise an error. I spent many hours trying to figure out why my `Optional`+`Computed` properties were always `null` on plan/apply.

### Steps to Reproduce
1. Apply above patch to https://github.com/hashicorp/terraform-provider-scaffolding-framework
2. `go build`
3. `cd examples/provider`
4. `tf plan`

### PR DESCRIPTION
**Pull request by bflad**
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/590
Closes #930

Previously the logic handling attribute `Default` values would silently ignore any type errors, which would lead to confusing planning data behaviors. This updates the logic to raise those error properly and adds covering unit testing.

These error messages are using the underlying `tftypes` type system errors which is currently a pragmatic compromise throughout various parts of the framework logic that bridges between both type systems to save additional type assertion logic and potential bugs relating to those conversions. In the future if the internal `tftypes` handling and exported fields are replaced with the framework type system types, this logic would instead return error messaging based on the framework type system errors.

This also will enhance the schema validation logic to check any `Default` response value and compare its type to the schema, which will raise framework type system errors during the `GetProviderSchema` RPC, or during schema unit testing if provider developers have implemented that additional testing.

### CODE REVIEW

File: internal/fwschemadata/data_default.go [hunk 1]
```diff
@@ -21,15 +21,15 @@ import (
...
 
 	configData := Data{
 		Description:    DataDescriptionConfiguration,
 		Schema:         d.Schema,
 		TerraformValue: configRaw,
 	}
 
-	// Errors are handled as richer diag.Diagnostics instead.
-	d.TerraformValue, _ = tftypes.Transform(d.TerraformValue, func(tfTypePath *tftypes.AttributePath, tfTypeValue tftypes.Value) (tftypes.Value, error) {
+	d.TerraformValue, err = tftypes.Transform(d.TerraformValue, func(tfTypePath *tftypes.AttributePath, tfTypeValue tftypes.Value) (tftypes.Value, error) {
```
Comment (austinvalle) [inline internal/fwschemadata/data_default.go:32]: This is awesome ❤️ . I don't want to stretch this PR too far, but do we want to just add similar error handling now to other places we follow a similar pattern with `tftypes.Transform`. Quick search shows:
- `(*Data).NullifyCollectionBlocks`
- `(*Data).ReifyNullCollectionBlocks`

File: resource/schema/list_attribute.go [hunk 2]
```diff
@@ -251,7 +251,26 @@ func (a ListAttribute) ValidateImplementation(ctx context.Context, req fwschema.
...
-		resp.Diagnostics.Append(nonComputedAttributeWithDefaultDiag(req.Path))
+	if a.ListDefaultValue() != nil {
+		if !a.IsComputed() {
+			resp.Diagnostics.Append(nonComputedAttributeWithDefaultDiag(req.Path))
+		}
+
+		// Validate Default implementation. This is safe unless the framework
+		// ever allows more dynamic Default implementations at which the
+		// implementation would be required to be validated at runtime.
+		// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/930
```
Comment (austinvalle) [inline resource/schema/list_attribute.go:262]: Interesting 👀

File: resource/schema/list_attribute.go [hunk 3]
```diff
@@ -251,7 +251,26 @@ func (a ListAttribute) ValidateImplementation(ctx context.Context, req fwschema.
...
+		}
+		defaultResp := &defaults.ListResponse{}
+
+		a.ListDefaultValue().DefaultList(ctx, defaultReq, defaultResp)
+
+		resp.Diagnostics.Append(defaultResp.Diagnostics...)
+
+		if a.ElementType != nil && !a.ElementType.Equal(defaultResp.PlanValue.ElementType(ctx)) {
+			resp.Diagnostics.Append(fwschema.AttributeDefaultElementTypeMismatchDiag(req.Path, a.ElementType, defaultResp.PlanValue.ElementType(ctx)))
+		}
```
Comment (austinvalle) [inline resource/schema/list_attribute.go:274]: Should we still check the equality of the element types if there are diagnostics retrieving the default?

> Same question applies to the other type comparisons in collections/nested attributes

**Review by austinvalle — APPROVED** [review]
LGTM 🚀 :shipit: - just a couple questions

**Review by bendbennett — COMMENTED** [review]
LGTM 🚀

File: internal/fwschemadata/data_default.go (hunk 1 above)
Comment (bflad) [reply internal/fwschemadata/data_default.go:32]: Created https://github.com/hashicorp/terraform-plugin-framework/issues/938 for tracking.

File: resource/schema/list_attribute.go (hunk 3 above)
Comment (bflad) [reply resource/schema/list_attribute.go:274]: I was debating this, but I think you are right. Even though `Default` value handling should be static/offline today, it would probably be annoying to see both diagnostics if, for example, you return an error diagnostic early without setting a default value with a fully realized/valid type. I'll hopefully have some time later today to update this.

Comment (bflad) [reply resource/schema/list_attribute.go]: Does this look okay? https://github.com/hashicorp/terraform-plugin-framework/pull/933/commits/6056a2883a9c829a0e3b235da2cb07b70f6990a6
