### PR TITLE
Fix `SingleNestedAttribute` validation failure

### LINKED ISSUE #112: SingleNestedAttributes validation failure if the attribute is not present in configuration
Relates #17.
With the latest (fad6afe33058c5a2581d1e424a50c7fc9a842ff3) code, suppose I have a schema like this:

```go
tfsdk.Schema{
	Attributes:  map[string]tfsdk.Attribute{
		"name": {
			Type:        types.StringType,
			Optional:    true,
		},

		"blah_configuration": {
			Attributes: tfsdk.SingleNestedAttributes(
				map[string]tfsdk.Attribute{
					"insights_enabled": {
						Type:        types.BoolType,
						Optional:    true,
					},
					"notifications_enabled": {
						Type:        types.BoolType,
						Optional:    true,
					},
				},
			),
			Optional: true,
		},
	},
}
```

and a configuration like this (`blah_configuration` not specified):

```hcl
resource "blah" "test" {
  name = "testing"
}
```

`terraform plan` errors:

```console
% terraform plan
╷
│ Error: Configuration Read Error
│ 
│   with blah.test,
│   on main.tf line 46, in resource "blah" "test":
│   46: resource "blah" "test" {
│ 
│ An unexpected error was encountered trying to read an attribute from the configuration. This is always an error in the provider. Please report the following to the
│ provider developer:
│ 
│ AttributeName("insights_enabled") still remains in the path: step cannot be applied to this value
╵
╷
│ Error: Configuration Read Error
│ 
│   with blah.test,
│   on main.tf line 46, in resource "blah" "test":
│   46: resource "blah" "test" {
│ 
│ An unexpected error was encountered trying to read an attribute from the configuration. This is always an error in the provider. Please report the following to the
│ provider developer:
│ 
│ AttributeName("notifications_enabled") still remains in the path: step cannot be applied to this value
╵
```

### PR DESCRIPTION
**Pull request by ewbankkit**
Closes #112.

Don't attempt validation if the attribute is missing from configuration.

### CODE REVIEW

**Review by kmoe — APPROVED** [review]

File: tfsdk/attribute.go [hunk 1]
```diff
@@ -341,18 +341,34 @@ func (a Attribute) validate(ctx context.Context, req ValidateAttributeRequest, r
...
+					Summary:   "Attribute Validation Error",
+					Detail:    "Attribute validation cannot walk schema. Report this to the provider developer:\n\n" + err.Error(),
+					Attribute: req.AttributePath,
+				})
+
+				return
+			}
 
-				resp.Diagnostics = nestedAttrResp.Diagnostics
+			if len(o.Attrs) > 0 {
```
Comment (paddycarver) [inline tfsdk/attribute.go:358]: Is there a reason this became necessary?

The for loop should cover this case, by just not entering the for loop, which it looks like is what this does?

Unless this is to cover the case where the schema has attributes defined, but Terraform sends a value omitting those attributes, which as far as I know, should never happen?

**Review by paddycarver — CHANGES_REQUESTED** [review]
Could we also add a .changelog entry? https://github.com/hashicorp/engineering-docs/blob/master/terraform/sdk/changelog.md

(I know that link is to a private repo, I'll open an issue to get it added to our contributing guide)

File: tfsdk/attribute.go (hunk 1 above)
Comment (ewbankkit) [reply tfsdk/attribute.go:358]: Correct, I'll remove the _if_.

Comment (ewbankkit) [reply tfsdk/attribute.go:358]: I think, as @kmoe mentions in https://github.com/hashicorp/terraform-plugin-framework/issues/112#issuecomment-905493498, it's the call to `tftypes.WalkAttributePath` in `Config.GetAttribute` called from `Attribute.validate` on the nested `Null` Attribute value that fails.

Comment (paddycarver) [reply tfsdk/attribute.go:358]: Could we use `o.Null` then, instead of checking the number of attributes?

Comment (ewbankkit) [reply tfsdk/attribute.go:358]: Let me take a look...

Comment (ewbankkit) [reply tfsdk/attribute.go]: Yes `!o.Null` works just as well.
Commit pushed.

Comment (avinashbot) [reply tfsdk/attribute.go]: Just tested this and hit a failure with unknown attributes; it looks like you'll need to add a check for `!o.Unknown` too.

Comment (ewbankkit) [reply tfsdk/attribute.go]: will do; thanks

File: .changelog/118.txt [hunk 2]
```diff
@@ -0,0 +1,3 @@
+```release-note:bug
+tfsdk: Don't attempt validation on a Null-valued `SingleNestedAttribute`
```
Comment (paddycarver) [inline .changelog/118.txt:2]:
```suggestion
tfsdk: Don't attempt validation on the nested attributes of a null or unknown `SingleNestedAttribute`
```

I think the validators on the attribute itself will still run, right? This is just for the nested attributes of that attribute?

**Review by paddycarver — CHANGES_REQUESTED** [review]

File: .changelog/118.txt (hunk 2 above)
Comment (ewbankkit) [reply .changelog/118.txt:2]: Correct.

File: tfsdk/attribute.go [hunk 3]
```diff
@@ -341,18 +341,34 @@ func (a Attribute) validate(ctx context.Context, req ValidateAttributeRequest, r
...
-				}
-				nestedAttrResp := &ValidateAttributeResponse{
-					Diagnostics: resp.Diagnostics,
-				}
+			o, ok := req.AttributeConfig.(types.Object)
 
-				nestedAttr.validate(ctx, nestedAttrReq, nestedAttrResp)
+			if !ok {
+				err := fmt.Errorf("unknown attribute value type (%T) for nesting mode (%T) at path: %s", req.AttributeConfig, nm, req.AttributePath)
+				resp.Diagnostics = append(resp.Diagnostics, &tfprotov6.Diagnostic{
```
Comment (paddycarver) [inline tfsdk/attribute.go:348]: Really sorry to do this to you, @ewbankkit, but could you update to use the helpers added by #110? Just want to keep our consistency @bflad worked so hard to introduce. 😦 

Sorry, ping me in chat when you do that and we'll get it merged straightaway before something else comes up. Thanks so much for the patience on this.

**Review by paddycarver — CHANGES_REQUESTED** [review]
