### PR TITLE
function: Add validation for parameter name conflicts and update defaulting logic

### LINKED ISSUE #926: function: Consider preventing parameter name conflicts in schema validation
### Module version
```
v1.5.0
```

### Use-cases

When building a provider-defined function with plugin framework, it is currently possible to create a function schema that is invalid, where two parameters (variadic or not) have the same name. When this occurs, you'll receive an error message from validation in Terraform like:

```bash
│ Error: Failed to load plugin schemas
│ 
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/austinvalle/sandbox: provider
│ registry.terraform.io/austinvalle/sandbox function "test_func" reuses name "param" for both parameters 0 and 1..
```

```bash
│ Error: Failed to load plugin schemas
│ 
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/austinvalle/sandbox: provider
│ registry.terraform.io/austinvalle/sandbox function "test_func" reuses name "param" for both parameter 0 and its variadic parameter..
```

Notably, this kind of invalid schema can be achieved inadvertently by omitting the parameter names in your function definition, which the framework currently defaults each name to `param`:

```go
func (f *TestFunction) Definition(ctx context.Context, req function.DefinitionRequest, resp *function.DefinitionResponse) {
	resp.Definition = function.Definition{
		Parameters: []function.Parameter{
			function.StringParameter{}, // defaults to param
			function.StringParameter{}, // defaults to param
		},
		VariadicParameter: function.StringParameter{}, // defaults to param
		Return:            function.Int64Return{},
	}
}
```

The full Terraform validation logic can be found here: https://github.com/hashicorp/terraform/blob/82361afd73ae5abb778d50e3b500fc08c2b04393/internal/terraform/context_plugins.go#L143-L168

### Current Workaround

The workaround is to explicitly name each parameter (which we would already recommend for all functions):

```go
func (f *TestFunction) Definition(ctx context.Context, req function.DefinitionRequest, resp *function.DefinitionResponse) {
	resp.Definition = function.Definition{
		Parameters: []function.Parameter{
			function.StringParameter{
				Name: "param1",
			},
			function.StringParameter{
				Name: "param2",
			},
		},
		VariadicParameter: function.StringParameter{
			Name: "varparam",
		},
		Return: function.Int64Return{},
	}
}
```

### Proposal

- The framework logic for defaulting function parameter names should be updated to ensure each parameter name is unique. We could potentially employ a strategy of:
  - Defaulting parameter names to `param{index number of parameter}` => `param1`
  - Defaulting variadic parameter name to `varparam`
- We may also want to consider adding validation logic to ensure the final function definition we send to Terraform has no conflicts if explicitly set:
```go
func (f *TestFunction) Definition(ctx context.Context, req function.DefinitionRequest, resp *function.DefinitionResponse) {
	resp.Definition = function.Definition{
		Parameters: []function.Parameter{
			function.StringParameter{
				Name: "paramdup",
			},
			function.StringParameter{
				Name: "paramdup",
			},
		},
		VariadicParameter: function.StringParameter{
			Name: "paramdup",
		},
		Return: function.Int64Return{},
	}
}
```

### References

- Originally found in: https://github.com/hashicorp/terraform-plugin-framework/pull/923#discussion_r1492511249

### PR DESCRIPTION
**Pull request by austinvalle**
Closes #926 

This PR contains two fixes:
- Validation errors will now be raised if conflicting parameter names (including the variadic parameter) exist in a `function.Definition` during the `GetProviderSchema` RPC.
- The default values and logic were also updated to ensure multiple empty `function.Parameter` names don't have conflicting names.
  - This fix required refactoring where the logic for defaulting occurred

### CODE REVIEW

File: internal/toproto6/function.go [hunk 1]
```diff
@@ -30,32 +29,39 @@ func Function(ctx context.Context, fw function.Definition) *tfprotov6.Function {
...
 // FunctionParameter returns the *tfprotov6.FunctionParameter for a
 // function.Parameter.
-func FunctionParameter(ctx context.Context, fw function.Parameter) *tfprotov6.FunctionParameter {
-	if fw == nil {
+func FunctionParameter(ctx context.Context, def function.Definition, param function.Parameter, position int) *tfprotov6.FunctionParameter {
+	if param == nil {
 		return nil
 	}
 
+	// TODO: what should we do with the diags? This should never happen
```
Comment (austinvalle) [inline internal/toproto6/function.go:50]: Open question: I'm not really sure how best to handle a `diag` here without fully refactoring all of this logic (which we can do)

Same question applies to `internal/toproto5/function.go`

File: function/definition.go [hunk 2]
```diff
@@ -108,6 +129,42 @@ func (d Definition) ValidateImplementation(ctx context.Context) diag.Diagnostics
 		)
 	}
 
+	paramNames := make(map[string]int, len(d.Parameters))
+	for pos := range d.Parameters {
+		// TODO: what should we do with the diags? This should never happen
+		name, _ := d.ParameterName(ctx, pos)
```
Comment (austinvalle) [inline function/definition.go:135]: Open question: Should I still return this `diag`?

> Same question applies to the variadic logic below

File: function/definition.go [hunk 3]
```diff
@@ -85,6 +85,27 @@ func (d Definition) Parameter(ctx context.Context, position int) (Parameter, dia
 	return d.Parameters[position], nil
 }
 
+// ParameterName returns the Parameter name for a given argument position. This will be the return
+// from the `(Parameter).GetName` function or a default value. An error diagnostic is raised if the
+// position is outside the expected arguments.
+func (d Definition) ParameterName(ctx context.Context, position int) (string, diag.Diagnostics) {
```
Comment (austinvalle) [inline function/definition.go:91]: I put this logic here to allow the defaulting logic to be shared by the `internal/toproto{5/6}` packages and the `ValidateImplementation` logic below.

Perhaps there is another way to approach this?

**Review by bflad — COMMENTED** [review]
Great work so far! Curious what you think about these. 👍

File: website/docs/plugin/framework/functions/documentation.mdx [hunk 4]
```diff
@@ -47,11 +47,11 @@ Each [parameter type](/terraform/plugin/framework/functions/parameters), whether
...
+| `Name` | Single word or abbreviation of parameter for function signature generation. If name is not provided, will default to the prefix "param" with a suffix of the position the parameter is in the function definition. (`param1`, `param2`, etc.). If the parameter is variadic, the default name will be `varparam`. |
 | `Description` | Documentation about the parameter and its expected values in plaintext format. |
 | `MarkdownDescription` | Documentation about the parameter and its expected values in Markdown format. |
 
-The name is only for documentation purposes and helpful when there is a need to disambiguate between multiple parameters, such as the words `cidr` and `ip` in a generated function signature like `cidr_contains_ip(cidr string, ip string) bool`.
+The name must be unique in the context of the [function definition](/terraform/plugin/framework/functions/implementation#definition-method) and is only for documentation purposes. The name can be helpful when there is a need to disambiguate between multiple parameters, such as the words `cidr` and `ip` in a generated function signature like `cidr_contains_ip(cidr string, ip string) bool`.
```
[the remark this answers is not in the document]
Comment (austinvalle) [reply website/docs/plugin/framework/functions/documentation.mdx:54]: Ah okay, I like the phrasing you used 👍🏻

File: function/definition.go (hunk 3 above)
Comment (austinvalle) [reply function/definition.go]: I'm good with the first suggestion here, the small amount of duplicated logic isn't a big deal (which is what I was originally trying to avoid)

Also updated the doc string for `(function.Parameter).GetName()`

Check out 858ddbb0662c5223614de73b952033018cb6f2ec

File: internal/toproto6/function.go (hunk 1 above)
Comment (austinvalle) [reply internal/toproto6/function.go]: Newest changes avoid diags by duplicating the logic ⚡

File: function/definition.go (hunk 2 above)
Comment (austinvalle) [reply function/definition.go]: Newest changes avoid diags by duplicating the logic ⚡

File: website/docs/plugin/framework/functions/documentation.mdx [hunk 5]
```diff
@@ -47,11 +47,11 @@ Each [parameter type](/terraform/plugin/framework/functions/parameters), whether
 
 | Field Name | Description |
 |---|---|
-| `Name` | Single word or abbreviation of parameter for function signature generation, defaults to `param`. |
+| `Name` | Single word or abbreviation of parameter for function signature generation. If name is not provided, will default to the prefix "param" with a suffix of the position the parameter is in the function definition. (`param1`, `param2`, etc.). If the parameter is variadic, the default name will be `varparam`. |
```
Comment (bendbennett) [inline website/docs/plugin/framework/functions/documentation.mdx:50]:
```suggestion
| `Name` | Single word or abbreviation of parameter for function signature generation. If name is not provided, will default to the prefix "param" with a suffix of the position the parameter is in the function definition (e.g., `param1`, `param2`). If the parameter is variadic, the default name will be `varparam`. |
```

Supernit

**Review by bendbennett — APPROVED** [review]
LGTM 🚀

**Review by bflad — APPROVED** [review]
Looks good to me 🚀  Nice work.
