### PR TITLE
tfsdk: Check ProposedNewState for State differences before marking unknowns for Computed-only attributes in plans

### LINKED ISSUE #181: PlanResourceChange Always Showing Differences
### Module version

```
cf6f24087d3af45f583d0736c6ed841243d23653 (post v0.4.1, pre v0.4.2)
```

### Relevant provider source code

Any schema with `Computed` only attributes. For example, `hashicups-pf`:

```go
func (r resourceOrderType) GetSchema(_ context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{
		Attributes: map[string]tfsdk.Attribute{
			"id": {
				Type: types.StringType,
				// When Computed is true, the provider will set value --
				// the user cannot define the value
				Computed: true,
			},
			"last_updated": {
				Type:     types.StringType,
				Computed: true,
			},
			"items": {
				// If Required is true, Terraform will throw error if user
				// doesn't specify value
				// If Optional is true, user can choose to supply a value
				Required: true,
				Attributes: tfsdk.ListNestedAttributes(map[string]tfsdk.Attribute{
					"quantity": {
						Type:     types.NumberType,
						Required: true,
					},
					"coffee": {
						Required: true,
						Attributes: tfsdk.SingleNestedAttributes(map[string]tfsdk.Attribute{
							"id": {
								Type:     types.NumberType,
								Required: true,
							},
							"name": {
								Type:     types.StringType,
								Computed: true,
							},
							"teaser": {
								Type:     types.StringType,
								Computed: true,
							},
							"description": {
								Type:     types.StringType,
								Computed: true,
							},
							"price": {
								Type:     types.NumberType,
								Computed: true,
							},
							"image": {
								Type:     types.StringType,
								Computed: true,
							},
						}),
					},
				}, tfsdk.ListNestedAttributesOptions{}),
			},
		},
	}, nil
}
```

### Terraform Configuration Files

```hcl
resource "hashicups_order" "edu" {
  items = [{
    coffee = {
      id = 3
    }
    quantity = 2
    }, {
    coffee = {
      id = 1
    }
    quantity = 2
    }
  ]
}
```

### Expected Behavior

With no configuration changes (e.g. v0.4.1 behavior):

```console
hashicups_order.edu: Refreshing state... [id=1]

No changes. Your infrastructure matches the configuration.
```

### Actual Behavior

With no configuration changes:

```console
$ terraform apply
...
hashicups_order.edu: Refreshing state... [id=1]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # hashicups_order.edu will be updated in-place
  ~ resource "hashicups_order" "edu" {
      ~ id           = "1" -> (known after apply)
      ~ items        = [
          ~ {
            ~ coffee   = {
              + description = (known after apply)
                id          = 3
              ~ image       = "/nomad.png" -> (known after apply)
              ~ name        = "Nomadicano" -> (known after apply)
              ~ price       = 150 -> (known after apply)
              ~ teaser      = "Drink one today and you will want to schedule another" -> (known after apply)
            }
              # (1 unchanged attribute hidden)

            ~ coffee   = {
              + description = (known after apply)
                id          = 1
              ~ image       = "/packer.png" -> (known after apply)
              ~ name        = "Packer Spiced Latte" -> (known after apply)
              ~ price       = 350 -> (known after apply)
              ~ teaser      = "Packed with goodness to spice up your images" -> (known after apply)
            }
              # (2 unchanged attributes hidden)
          },
        ]
      ~ last_updated = "Tuesday, 28-Sep-21 11:53:27 EDT" -> (known after apply)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply` (with no configuration changes)

### References

- #175 
- #176

### PR DESCRIPTION
**Pull request by bflad**
Closes #181
Reference: https://github.com/hashicorp/terraform/blob/main/docs/resource-instance-change-lifecycle.md 

`ProposedNewState` is the merged `PriorState` and `Configuration`. This allows us to verify if any configuration changes have occurred.

Previously, any `Computed` attributes would always trigger plan differences due to the unknown marking.

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # hashicups_order.edu will be updated in-place
  ~ resource "hashicups_order" "edu" {
      ~ id           = "1" -> (known after apply)
      ~ items        = [
          ~ {
            ~ coffee   = {
              + description = (known after apply)
                id          = 3
              ~ image       = "/nomad.png" -> (known after apply)
              ~ name        = "Nomadicano" -> (known after apply)
              ~ price       = 150 -> (known after apply)
              ~ teaser      = "Drink one today and you will want to schedule another" -> (known after apply)
            }
              # (1 unchanged attribute hidden)

            ~ coffee   = {
              + description = (known after apply)
                id          = 1
              ~ image       = "/packer.png" -> (known after apply)
              ~ name        = "Packer Spiced Latte" -> (known after apply)
              ~ price       = 350 -> (known after apply)
              ~ teaser      = "Packed with goodness to spice up your images" -> (known after apply)
            }
              # (2 unchanged attributes hidden)
          },
        ]
      ~ last_updated = "Tuesday, 28-Sep-21 11:53:27 EDT" -> (known after apply)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

This change limits the unknown marking to only be performed when there is actually a change between the `ProposedNewState` and `State`.

Without a configuration change:

```
No changes. Your infrastructure matches the configuration.
```

With a configuration change:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # hashicups_order.edu will be updated in-place
  ~ resource "hashicups_order" "edu" {
      ~ id           = "1" -> (known after apply)
      ~ items        = [
          ~ {
            ~ coffee   = {
              + description = (known after apply)
                id          = 3
              ~ image       = "/nomad.png" -> (known after apply)
              ~ name        = "Nomadicano" -> (known after apply)
              ~ price       = 150 -> (known after apply)
              ~ teaser      = "Drink one today and you will want to schedule another" -> (known after apply)
            }
              # (1 unchanged attribute hidden)

            ~ coffee   = {
              + description = (known after apply)
              ~ id          = 1 -> 2
              ~ image       = "/packer.png" -> (known after apply)
              ~ name        = "Packer Spiced Latte" -> (known after apply)
              ~ price       = 350 -> (known after apply)
              ~ teaser      = "Packed with goodness to spice up your images" -> (known after apply)
            }
              # (2 unchanged attributes hidden)
          },
        ]
      ~ last_updated = "Tuesday, 28-Sep-21 11:53:27 EDT" -> (known after apply)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

As a followup, it may be necessary to invoke two passes of attribute and resource plan modifiers to ensure any changes captured by those modifiers triggers the unknown marking. As it stands now, a plan with no configuration changes, but changes due to plan modifiers will not correctly trigger the unknown marking. See also: https://github.com/hashicorp/terraform-plugin-framework/issues/183

### CODE REVIEW

File: tfsdk/serve_test.go [hunk 1]
```diff
@@ -1719,6 +1719,7 @@ func TestServerPlanResourceChange(t *testing.T) {
 				"favorite_colors": tftypes.NewValue(tftypes.List{ElementType: tftypes.String}, []tftypes.Value{
 					tftypes.NewValue(tftypes.String, "red"),
 					tftypes.NewValue(tftypes.String, "orange"),
+					tftypes.NewValue(tftypes.String, "yellow"),
```
Comment (bflad) [inline tfsdk/serve_test.go:1722]: This is a test fix since the configuration contained it, so the proposedNewState would also contain it.

File: tfsdk/serve_test.go [hunk 2]
```diff
@@ -1738,10 +1739,47 @@ func TestServerPlanResourceChange(t *testing.T) {
...
```
Comment (bflad) [inline tfsdk/serve_test.go:1742]: This is a test fix since the proposed new state contained it, so the planned state would also contain it.

File: tfsdk/serve_test.go [hunk 3]
```diff
@@ -1783,7 +1821,199 @@ func TestServerPlanResourceChange(t *testing.T) {
 			resourceType:         testServeResourceTypeTwoType,
 			expectedPlannedState: tftypes.NewValue(testServeResourceTypeTwoType, nil),
 		},
-		"three_nested_computed_unknown": {
```
Comment (bflad) [inline tfsdk/serve_test.go:1786]: NB: This was renamed to `three_nested_computed_nested_configuration_change` as seen below the next Git diff, just to capture the additional nuance between the two new test cases and the original.

File: tfsdk/serve_resource_attribute_plan_modifiers_test.go [hunk 4]
```diff
@@ -92,6 +92,10 @@ func (rt testServeResourceTypeAttributePlanModifiers) GetSchema(_ context.Contex
 				Type:          types.StringType,
 				PlanModifiers: []AttributePlanModifier{testAttrDefaultValueModifier{}},
 			},
+			"computed_string_no_modifiers": {
```
Comment (bflad) [inline tfsdk/serve_resource_attribute_plan_modifiers_test.go:95]: Additional attribute on this resource to allow us to further verify plan unknown marking, since this resource has attribute plan modifiers and allowed me to catch #183 for the future. It does not have to be part of this pull request though. 😄

**Review by bflad — COMMENTED** [review]
Some additional breadcrumbs for review, since the real change was just adding `&& !plan.Equal(state)`

**Comment by kmoe** [comment]
Getting a slightly unexpected result with this.

Configuration:
```hcl
provider "hashicups" {
  username = "education"
  password = "test123"
  host     = "http://localhost:19090"
}

resource "hashicups_order" "edu" {
  items = [{
    coffee = {
      id = 3
    }
    quantity = 2
    }, {
    coffee = {
      id = 2
    }
    quantity = 2
    }
  ]
}
```

### Steps
1. Run `terraform apply` and proceed with `yes`
2. Change the second coffee id to `1`
3. Run `terraform apply` and proceed with `yes`

### Result

The output from the second apply is as in the PR description, but when actually running the apply we get this:
```
  Enter a value: yes

hashicups_order.edu: Modifying... [id=1]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to hashicups_order.edu, provider
│ "provider[\"registry.terraform.io/hashicorp/hashicups\"]" produced an unexpected new value: .items: was
│ cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"coffee":cty.ObjectVal(map[string]cty.Value{"description":cty.UnknownVal(cty.String),
│ "id":cty.NumberIntVal(3), "image":cty.UnknownVal(cty.String), "name":cty.UnknownVal(cty.String),
│ "price":cty.UnknownVal(cty.Number), "teaser":cty.UnknownVal(cty.String)}), "quantity":cty.NumberIntVal(2)}),
│ cty.ObjectVal(map[string]cty.Value{"coffee":cty.ObjectVal(map[string]cty.Value{"description":cty.UnknownVal(cty.String),
│ "id":cty.NumberIntVal(2), "image":cty.UnknownVal(cty.String), "name":cty.UnknownVal(cty.String),
│ "price":cty.UnknownVal(cty.Number), "teaser":cty.UnknownVal(cty.String)}),
│ "quantity":cty.NumberIntVal(2)})}), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Review by kmoe — APPROVED** [review]
